### ISSUE TITLE
stringr and dplyr dependencies

### ISSUE THREAD

**Issue by carlganz** [ropenscilabs/available#11]
Uses `stringr`:

https://github.com/ropenscilabs/available/blob/9e26973d6d2534d70cad3e245cb05ad7b4be9bf5/R/github.R#L39

https://github.com/ropenscilabs/available/blob/9e07e17acc1d307500ac20a9b7fe0f5191ef2622/R/bad_words.R#L20

Uses `dplyr`:

https://github.com/ropenscilabs/available/blob/9e26973d6d2534d70cad3e245cb05ad7b4be9bf5/R/github.R#L36

There are base R solutions in each case, so we can try to remove

**Comment by gaborcsardi** [comment]
`tidytext` requires `dplyr`, so this is not so important imo
