### ISSUE TITLE
enhancement: in-depth checking

### ISSUE THREAD

**Issue by lorenzwalthert** [ropenscilabs/available#15]
Have you thought about extending the package so it can:
* check whether function names are used by other packages (so you don't create another function with the same name by accident)?
* check whether class names are used by other packages (e.g. `data.frame`) to avoid method dispatch issues?

That might be handy too, even thought probably more complicated to implement.

**Comment by jimhester** [comment]
I agree they are useful, however they are much more complicated to implement and probably beyond the scope of this package.

**Comment by lorenzwalthert** [comment]
So I guess we can close this then.
