### ISSUE TITLE
Search names in regular Dictionaries

### ISSUE THREAD

**Issue by jimhester** [ropenscilabs/available#2]
Including English and possibly other languages.

**Comment by jimhester** [comment]
Find one from https://www.programmableweb.com/category/dictionary/api

**Comment by rctatman** [comment]
**Pre-processing to convert name to search string to send to dictionaries:**
- try both with and without final R or r
- assume capital letter in the middle of a name is a on word boundary (test both with and without if capital letter is R), but not necessarily the first letter of a word
- assume any non-alpha character is a word boundary (strip & replace with space)

**Sample input-ouput:**
"tidyr" -> "tidy", "r", "tidyr"
"bigIdea" -> "bigi", "dea","big", "idea", "bigidea"
"bigRidea" -> "bigr", "idea", "big", "ridea", "big", "r", "idea", "bigridea"
"big2idea" -> "big", "idea", "big2idea"

**Weird edge cases (real package names):**
- GeneralizedUmatrix (umatrix not a real word)
- snakecase (no way to identify snake and case as separate words, out of scope @ this time)
- xLLiM (why?)
