### ISSUE TITLE
Feature Request: add option to suppress opening of web pages

### ISSUE THREAD

**Issue by zkamvar** [ropenscilabs/available#24]
Just as the title says, It would be nice to have this feature for situations where one doesn't want to open the default browser.

**Comment by jimhester** [comment]
Yes this is a good suggestion, thank you for opening the issue

**Comment by jimhester** [comment]
This was added with https://github.com/ropenscilabs/available/commit/e39682aaf8d1386155df545e5550124b325f8fa8
