### ISSUE TITLE
Search abbreviations

### ISSUE THREAD

**Issue by jimhester** [ropenscilabs/available#3]
http://www.abbreviations.com/services/v1/

**Comment by carlganz** [comment]
This API does not appear to be free, but I could be misreading the docs.

From [website](http://www.abbreviations.com/api.php):

>In order to get started sign up to get your developer token and once we've reviewed your information, we'll activate your account so you can begin developing on the API. All we require is that you'll place a credit line at a visible location on your final product.

**Comment by jimhester** [comment]
Looks like it is free for a small # of queries 

> free to use for up to 100 queries per day.
