### ISSUE TITLE
r-lib/boxes should be r-lib/cli ?

### ISSUE THREAD

**Issue by russHyde** [ropenscilabs/available#31]
Hi,
Should the import-dependency on the package 'boxes' and the remote library "r-libs/boxes" be present? I get a "no package `boxes` at the repositories" warning when I try to `install_github("available")`

When I search for this package in github, I get redirected to 'r-libs/cli'. The latter does contain the `rule()` function that is mentioned in `available.R::45` (the only call to `boxes` in `available` as of 2017-10-24). Seems like 'boxes' has been renamed 'cli' to me.

All the best

**Comment by jimhester** [comment]
Fixed by https://github.com/ropenscilabs/available/commit/46398298880b9b7317d9df3ac1f77bd8dd1a01ff
