### ISSUE TITLE
install_github() fails at dependency 'boxes'

### ISSUE THREAD

**Issue by BarkleyBG** [ropenscilabs/available#32]
I was attempting to install but ran into an error with package dependencies. Here's short output:

```
> devtools::install_github("ropenscilabs/available")
Downloading GitHub repo ropenscilabs/available@master
from URL https://api.github.com/repos/ropenscilabs/available/zipball/master
Installing available
[...etc...]
ERROR: dependency 'boxes' is not available for package 'available'
* removing 'C:/Program Files/R/R-3.3.0/library/available'
Installation failed: Command failed (1)
```

I can provide `sessionInfo()` if you'd like.

I'm pretty sure this is the same as #31, but I'm filing a separate issue in case this has a different root cause. 

Thanks!

**Comment by jimhester** [comment]
Fixed by https://github.com/ropenscilabs/available/commit/46398298880b9b7317d9df3ac1f77bd8dd1a01ff
