### ISSUE TITLE
trailing r of name shaved off in some checks

### ISSUE THREAD

**Issue by rnuske** [ropenscilabs/available#35]
some checks ignore the trailing r of name (such as Abbreviations, Wikipedia, Wikitionary, Urban Dictionary). 

```
> available(name='loder', browse=FALSE)
── loder ─────────────────────────────────────────────────────────────────────────────────────────────────────
Name valid: ✔
Available on CRAN: ✖ 
Available on Bioconductor: ✔
Available on GitHub:  ✔ 
Bad Words: ✔
Abbreviations: http://www.abbreviations.com/lode
Wikipedia: https://en.wikipedia.org/wiki/lode
Wiktionary: https://en.wiktionary.org/wiki/lode
Urban Dictionary:
  oppersite of a chode long but thin
  Tags: lawd loaded loded lawde lod lodd loser loaded niilo pwned sperm
  http://lode.urbanup.com/1291571
Sentiment:???
```

It might be caused by the disassembling of name, to check parts of name against online reference works. This seems to be problematic with short names.

**Comment by alexpghayes** [comment]
I think it would be nice to have an argument `strip_trailing_r` that defaults to `TRUE` but can be set to `FALSE`. For example, the current results for `available("linear")` are a little confusing if you aren't familiar with the convention of adding `r` to the end of a package name.

**Comment by jimhester** [comment]
This was actually due to a bug, the regular expression was using a negative lookahead rather than a look behind. Rs proceeded by a vowel were never meant to be trimmed.
