### ISSUE TITLE
Use of glue::collapse() should be updated to glue_collapse

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [ropenscilabs/available#40]
The `available` function produces the following warning:

```
Warning message:
'glue::collapse' is deprecated.
Use 'glue_collapse' instead.
See help("Deprecated") and help("glue-deprecated"). 
```

I believe the following three lines need to be updated with glue_collapse:

https://github.com/ropenscilabs/available/blob/4ad19d1344197dfa9c2652b258ca04c08d09cafa/R/bad_words.R#L20

https://github.com/ropenscilabs/available/blob/4ad19d1344197dfa9c2652b258ca04c08d09cafa/R/bad_words.R#L35

https://github.com/ropenscilabs/available/blob/d2a9e23dea80a14f258dcdfb9b38a1599c502757/R/namr.R#L37

Happy to do a PR too.

**Comment by jimhester** [comment]
Fixed by https://github.com/ropenscilabs/available/commit/2a54276f8c1ebe3c77f907fecf90d626b181730a
