### ISSUE TITLE
version inconsistent with CRAN

### ISSUE THREAD

**Issue by russHyde** [ropenscilabs/available#42]
Hi,
the version number in master/DESCRIPTION is 1.0.0, but version 1.0.1 is available on [CRAN](https://cran.r-project.org/web/packages/available/index.html).
Is the source code stored in master otherwise consistent with the CRAN version?
All the best

**Comment by jimhester** [comment]
I had not pushed the commits back to GitHub, this is now done. Thanks for opening the issue.
