### ISSUE TITLE
badwords

### ISSUE THREAD

**Issue by carlganz** [ropenscilabs/available#9]
https://github.com/web-mech/badwords

**Comment by carlganz** [comment]
Other possible lists of foul language are available online

**Comment by carlganz** [comment]
https://github.com/t-davidson/hate-speech-and-offensive-language

**Comment by rctatman** [comment]
Not bad words, but super-common English stop-words that you might what to avoid in package names? https://github.com/arc12/Text-Mining-Weak-Signals/wiki/Standard-set-of-english-stopwords

**Comment by rctatman** [comment]
Also, this might be a good resource for checking against a multilingual dataset, but it doesn't look like it has an API: http://wordsafety.com/

**Comment by rctatman** [comment]
multilingual resource: https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words

**Comment by carlganz** [comment]
```{R}
#' List of bad words
#'
#' @note See \url{https://github.com/web-mech/badwords}


bad_words <- memoise::memoise(function() {
  url <- "https://raw.githubusercontent.com/web-mech/badwords/master/lib/lang.json"

  jsonlite::fromJSON(url)[[1]]

})

check_bad_words <- function(name) {
  # check each bad word to see if in package name
  check <- vapply(bad_words(), function(word) {
    stringr::str_detect(name, word)
  }, logical(1))

  if(any(check)) {
    bad <- bad_words()[check]
    stop(
      sprintf("Your package name includes the bad word(s): %s", paste0(bad, collapse = ", ")),
      call. = FALSE
    )
  }

  print("Your package name does not include any bad words")
  invisible(TRUE)
}

```
